backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "/public/assets/blog"
public_folder: "/assets/blog"

collections:
  - name: "blog"
    label: "blog"
    folder: "src/blog" # where to create a new post
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
# name => Post type identifier, used in routes. Must be unique.
# label => What the admin UI calls the post type.
# folder => Where files of this type are stored, relative to the repo root.
# create => Set to true to allow users to create new files in this collection.
#  slug => Template for filenames. {{year}}, {{month}}, and {{day}} pulls from the post's date field or save date. {{slug}} is a url-safe version of the post's title. Default is simply {{slug}}.
# fields => Fields listed here are shown as fields in the content editor, then saved as front matter at the beginning of the document (except for body, which follows the front matter). Each field contains the following properties:
## label: Field label in the editor UI.
## name: Field name in the document front matter.
## widget: Determines UI style and value data type (details below).
## default (optional): Sets a default value for the field.
